# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/ruby:2.6.0-node

        environment:
            BUNDLE_PATH: ~/repo/vendor/bundle
            BUNDLER_VERSION: 2.0.1

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "Gemfile.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Update bundle
                  command: gem install bundler:2.0.1

            - run:
                  name: Bundle Install
                  command: bundle check || bundle install --path vendor/bundle

            - save_cache:
                  paths:
                      - ./vendor/bundle
                  key: v1-dependencies-{{ checksum "Gemfile.lock" }}

            # Build
            - run:
                  name: Build
                  command: bundle exec jekyll build

            # run tests!
            - run:
                  name: HTMLProofer tests
                  command: |
                      bundle exec htmlproofer \
                          --allow-hash-href \
                          --check-favicon  \
                          --check-html \
                          --disable-external \
                          --assume-extension \
                          ./_site \


            - persist_to_workspace:
                  root: ./
                  paths:
                      - _site

    deploy:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout
            - run: yarn install

            - attach_workspace:
                  at: ./

            - run: node .circleci/deploy.js

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
